language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test ./... -coverprofile cp.out
  - $GOPATH/bin/goveralls -coverprofile cp.out -service=travis-ci
